"""
Template definitions for E-way Bill API
"""

def get_eway_bill_template():
    """Returns the standard E-way bill template structure"""
    return {
        "userGstin": "05AAABB0639G1Z8",
        "supply_type": "outward",
        "sub_supply_type": "Supply",
        "sub_supply_description": "",
        "document_type": "Tax Invoice",
        "document_number": "IMP/25/XXX",
        "document_date": "20/09/2025",
        "gstin_of_consignor": "05AAABB0639G1Z8",
        "legal_name_of_consignor": "Your Company Name",
        "address1_of_consignor": "Your Address Line 1",
        "address2_of_consignor": "Your Address Line 2",
        "place_of_consignor": "Your City",
        "pincode_of_consignor": 400001,
        "state_of_consignor": "YOUR_STATE",
        "actual_from_state_name": "YOUR_STATE",
        "gstin_of_consignee": "05AAABC0181E1ZE",
        "legal_name_of_consignee": "Customer Name",
        "address1_of_consignee": "Customer Address 1",
        "address2_of_consignee": "Customer Address 2",
        "place_of_consignee": "Customer City",
        "pincode_of_consignee": 248001,
        "state_of_supply": "CUSTOMER_STATE",
        "actual_to_state_name": "CUSTOMER_STATE",
        "transaction_type": 3,
        "other_value": 0,
        "total_invoice_value": 560,
        "taxable_amount": 500,
        "cgst_amount": 30,
        "sgst_amount": 30,
        "igst_amount": 0,
        "cess_amount": 0,
        "cess_nonadvol_value": 0,
        "transporter_id": "",
        "transporter_name": "",
        "transporter_document_number": "",
        "transporter_document_date": "",
        "transportation_mode": "",
        "transportation_distance": "",
        "vehicle_number": "",
        "vehicle_type": "",
        "generate_status": 1,
        "data_source": "erp",
        "user_ref": "",
        "location_code": "",
        "eway_bill_status": "ABC",
        "auto_print": "N",
        "email": "",
        "delete_record": "N",
        "itemList": [
            {
                "product_name": "Product Name",
                "product_description": "Product Description",
                "hsn_code": "1001",
                "quantity": 1,
                "unit_of_product": "BOX",
                "cgst_rate": 6,
                "sgst_rate": 6,
                "igst_rate": 0,
                "cess_rate": 0,
                "cessNonAdvol": 0,
                "taxable_amount": 100
            }
        ]
    }