"""
Test script: Generate E-Way Bill using data from existing EWB 451693644839
Consignor: MODERN LOCK MFG. CO. (09AABFM8846M1ZM)
Consignee: M.A ENTERPRISES (09ASMPS6146H1Z5)
"""
import json
import sys
import os

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from services.generate_ewaybill_service import generate_ewaybill

payload = {
    "userGstin": "09COVPS5556J1ZT",
    "supply_type": "outward",
    "sub_supply_type": "Supply",
    "sub_supply_description": "",
    "document_type": "Tax Invoice",
    "document_number": "MLMC/25-26/T001",
    "document_date": "14/03/2026",
    "gstin_of_consignor": "09AABFM8846M1ZM",
    "legal_name_of_consignor": "MODERN LOCK MFG. CO.",
    "address1_of_consignor": "RAMSON HOUSE KOTHI NO.1 BANNA DEVI, G.T.ROAD,ALIGARH",
    "address2_of_consignor": "",
    "place_of_consignor": "ALIGARH",
    "pincode_of_consignor": 202001,
    "state_of_consignor": "UTTAR PRADESH",
    "actual_from_state_name": "UTTAR PRADESH",
    "gstin_of_consignee": "09ASMPS6146H1Z5",
    "legal_name_of_consignee": "M.A ENTERPRISES",
    "address1_of_consignee": "127, DONDIPUR ALLAHABAD",
    "address2_of_consignee": "",
    "place_of_consignee": "ALLAHABAD",
    "pincode_of_consignee": 211003,
    "state_of_supply": "UTTAR PRADESH",
    "actual_to_state_name": "UTTAR PRADESH",
    "transaction_type": 1,
    "other_value": 0.07,
    "total_invoice_value": 357823,
    "taxable_amount": 303239.75,
    "cgst_amount": 27291.59,
    "sgst_amount": 27291.59,
    "igst_amount": 0,
    "cess_amount": 0,
    "cess_nonadvol_value": 0,
    "transporter_id": "09COVPS5556J1ZT",
    "transporter_name": "S S TRANSPORT CORPORATION",
    "transporter_document_number": "",
    "transporter_document_date": "",
    "transportation_mode": "Road",
    "transportation_distance": "563",
    "vehicle_number": "UP81CT9947",
    "vehicle_type": "Regular",
    "generate_status": 1,
    "data_source": "erp",
    "user_ref": "",
    "location_code": "",
    "eway_bill_status": "ABC",
    "auto_print": "N",
    "email": "",
    "delete_record": "N",
    "itemList": [
        {
            "product_name": "DOVE CAB HDL ROSE GOLD 8",
            "product_description": "DOVE CAB HDL ROSE GOLD 8",
            "hsn_code": "83024110",
            "quantity": 36,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2745
        },
        {
            "product_name": "ROUBLE CAB HDL BLACK 4",
            "product_description": "ROUBLE CAB HDL BLACK 4",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2610
        },
        {
            "product_name": "CURVY CAB HDL MATT CP 8",
            "product_description": "CURVY CAB HDL MATT CP 8",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3285
        },
        {
            "product_name": "DOVE CAB HDL ROSE GOLD 6",
            "product_description": "DOVE CAB HDL ROSE GOLD 6",
            "hsn_code": "83024110",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 7350
        },
        {
            "product_name": "DOVE CAB HDL ROSE GOLD 4",
            "product_description": "DOVE CAB HDL ROSE GOLD 4",
            "hsn_code": "83024110",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 5280
        },
        {
            "product_name": "DOVE CAB HDL CP 4",
            "product_description": "DOVE CAB HDL CP 4",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2550
        },
        {
            "product_name": "DOVE CAB HDL CP 6",
            "product_description": "DOVE CAB HDL CP 6",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3360
        },
        {
            "product_name": "DOVE CAB HDL CP 8",
            "product_description": "DOVE CAB HDL CP 8",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4260
        },
        {
            "product_name": "STYLE CAB HDL BLACK ROSE GOLD 4",
            "product_description": "STYLE CAB HDL BLACK ROSE GOLD 4",
            "hsn_code": "83024110",
            "quantity": 144,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 9900
        },
        {
            "product_name": "STYLE CAB HDL BLACK ROSE GOLD 12",
            "product_description": "STYLE CAB HDL BLACK ROSE GOLD 12",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 12480
        },
        {
            "product_name": "RAMSON LUDO M/P LOCK",
            "product_description": "RAMSON LUDO M/P LOCK",
            "hsn_code": "83013000",
            "quantity": 200,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 10000
        },
        {
            "product_name": "SS K 12 TOP CAB HDL TT 6",
            "product_description": "SS K 12 TOP CAB HDL TT 6",
            "hsn_code": "83024110",
            "quantity": 240,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3720
        },
        {
            "product_name": "H-PIPE BTB HDL 25 MM 12",
            "product_description": "H-PIPE BTB HDL 25 MM 12",
            "hsn_code": "83024110",
            "quantity": 10,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2100
        },
        {
            "product_name": "PUSH LOCK 32 MM",
            "product_description": "PUSH LOCK 32 MM",
            "hsn_code": "83013000",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3225
        },
        {
            "product_name": "PUSH LOCK 23 MM",
            "product_description": "PUSH LOCK 23 MM",
            "hsn_code": "83013000",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 5250
        },
        {
            "product_name": "DOVE CAB HDL ROSE GOLD 12",
            "product_description": "DOVE CAB HDL ROSE GOLD 12",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 8340
        },
        {
            "product_name": "DOVE CAB HDL CP 12",
            "product_description": "DOVE CAB HDL CP 12",
            "hsn_code": "83024110",
            "quantity": 48,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 6216
        },
        {
            "product_name": "STYLE CAB HDL BLACK ROSE GOLD 8",
            "product_description": "STYLE CAB HDL BLACK ROSE GOLD 8",
            "hsn_code": "83024110",
            "quantity": 90,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 10057.5
        },
        {
            "product_name": "DOLMA CAB HDL COPPER ROSE GOLD 8",
            "product_description": "DOLMA CAB HDL COPPER ROSE GOLD 8",
            "hsn_code": "83024110",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 9600
        },
        {
            "product_name": "DOLMA CAB HDL COPPER ROSE GOLD 12",
            "product_description": "DOLMA CAB HDL COPPER ROSE GOLD 12",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 8850
        },
        {
            "product_name": "CURVY CAB HDL ROSEGOLD 4",
            "product_description": "CURVY CAB HDL ROSEGOLD 4",
            "hsn_code": "83024110",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 9240
        },
        {
            "product_name": "CURVY CAB HDL ROSEGOLD 10",
            "product_description": "CURVY CAB HDL ROSEGOLD 10",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 5025
        },
        {
            "product_name": "ROUBLE CAB HDL BLACK 10",
            "product_description": "ROUBLE CAB HDL BLACK 10",
            "hsn_code": "83024110",
            "quantity": 12,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 1197
        },
        {
            "product_name": "ROUBLE CAB HDL BLACK 8",
            "product_description": "ROUBLE CAB HDL BLACK 8",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2167.5
        },
        {
            "product_name": "SS K 12 TOP CAB HDL TT 4",
            "product_description": "SS K 12 TOP CAB HDL TT 4",
            "hsn_code": "83024110",
            "quantity": 72,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 864
        },
        {
            "product_name": "R FORCE SILK CB LOCK D/A 75MM",
            "product_description": "R FORCE SILK CB LOCK D/A 75MM",
            "hsn_code": "83013000",
            "quantity": 360,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 13140
        },
        {
            "product_name": "RAMSON GIGA M/P LOCK",
            "product_description": "RAMSON GIGA M/P LOCK",
            "hsn_code": "83013000",
            "quantity": 525,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 17718.75
        },
        {
            "product_name": "ROXY CHEST HDL ROSE GOLD BLACK",
            "product_description": "ROXY CHEST HDL ROSE GOLD BLACK",
            "hsn_code": "83024110",
            "quantity": 480,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 18000
        },
        {
            "product_name": "CRIZAL PULL HDL SATIN 12",
            "product_description": "CRIZAL PULL HDL SATIN 12",
            "hsn_code": "83024110",
            "quantity": 24,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4350
        },
        {
            "product_name": "CRIZAL PULL HDL BLACK 12",
            "product_description": "CRIZAL PULL HDL BLACK 12",
            "hsn_code": "83024110",
            "quantity": 12,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2190
        },
        {
            "product_name": "SAFFOLA P/H GLOSSY 12",
            "product_description": "SAFFOLA P/H GLOSSY 12",
            "hsn_code": "83024110",
            "quantity": 40,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 6800
        },
        {
            "product_name": "CRIZAL PULL HDL PVD ROSE GOLD 12",
            "product_description": "CRIZAL PULL HDL PVD ROSE GOLD 12",
            "hsn_code": "83024110",
            "quantity": 20,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4800
        },
        {
            "product_name": "SAFFOLA P/H PVD GOLD 12",
            "product_description": "SAFFOLA P/H PVD GOLD 12",
            "hsn_code": "83024110",
            "quantity": 20,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3875
        },
        {
            "product_name": "Z ASTRO KNOB GOLD",
            "product_description": "Z ASTRO KNOB GOLD",
            "hsn_code": "83024110",
            "quantity": 420,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 10710
        },
        {
            "product_name": "Z ASTRO KNOB R/GOLD",
            "product_description": "Z ASTRO KNOB R/GOLD",
            "hsn_code": "83024110",
            "quantity": 192,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4896
        },
        {
            "product_name": "BESTIE CONC SATIN ROSE GOLD 4",
            "product_description": "BESTIE CONC SATIN ROSE GOLD 4",
            "hsn_code": "83024110",
            "quantity": 36,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2430
        },
        {
            "product_name": "BESTIE CONC SATIN ROSE GOLD 8",
            "product_description": "BESTIE CONC SATIN ROSE GOLD 8",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3150
        },
        {
            "product_name": "BESTIE CONC BLACK 4",
            "product_description": "BESTIE CONC BLACK 4",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2025
        },
        {
            "product_name": "BESTIE CONC BLACK 8",
            "product_description": "BESTIE CONC BLACK 8",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3150
        },
        {
            "product_name": "BESTIE CONC BLACK 10",
            "product_description": "BESTIE CONC BLACK 10",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4050
        },
        {
            "product_name": "ROXY CHEST HDL SATIN SS",
            "product_description": "ROXY CHEST HDL SATIN SS",
            "hsn_code": "83024110",
            "quantity": 48,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 1800
        },
        {
            "product_name": "CHARMS CAB HDL ANTQ GOLD 6",
            "product_description": "CHARMS CAB HDL ANTQ GOLD 6",
            "hsn_code": "83024110",
            "quantity": 12,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 930
        },
        {
            "product_name": "CHARMS CAB HDL ANTQ GOLD 4",
            "product_description": "CHARMS CAB HDL ANTQ GOLD 4",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3450
        },
        {
            "product_name": "CHARMS CAB HDL ANTQ GOLD 8",
            "product_description": "CHARMS CAB HDL ANTQ GOLD 8",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 5550
        },
        {
            "product_name": "CUT CONC HDL BLACK 4",
            "product_description": "CUT CONC HDL BLACK 4",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2100
        },
        {
            "product_name": "CUT CONC HDL BLACK 7",
            "product_description": "CUT CONC HDL BLACK 7",
            "hsn_code": "83024110",
            "quantity": 48,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4800
        },
        {
            "product_name": "ZIPO CABINET HDL BLACK 6",
            "product_description": "ZIPO CABINET HDL BLACK 6",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 2760
        },
        {
            "product_name": "Z ASTRO KNOB BLACK",
            "product_description": "Z ASTRO KNOB BLACK",
            "hsn_code": "83024110",
            "quantity": 276,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 6693
        },
        {
            "product_name": "Z DOODLE KNOB BLACK",
            "product_description": "Z DOODLE KNOB BLACK",
            "hsn_code": "83024110",
            "quantity": 120,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4650
        },
        {
            "product_name": "ALU ALTER HANDLE R/GOLD 4",
            "product_description": "ALU ALTER HANDLE R/GOLD 4",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 3300
        },
        {
            "product_name": "GEMINI ALU HDL BLACK 8",
            "product_description": "GEMINI ALU HDL BLACK 8",
            "hsn_code": "83024110",
            "quantity": 60,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 6000
        },
        {
            "product_name": "BESTIE CONC SATIN ROSE GOLD 10",
            "product_description": "BESTIE CONC SATIN ROSE GOLD 10",
            "hsn_code": "83024110",
            "quantity": 30,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 4050
        },
        {
            "product_name": "LAXI CHEST HDL BLACK",
            "product_description": "LAXI CHEST HDL  BLACK",
            "hsn_code": "83024110",
            "quantity": 144,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 8100
        },
        {
            "product_name": "OTU CHEST HDL MATT ROSE GOLD",
            "product_description": "OTU CHEST HDL MATT ROSE GOLD",
            "hsn_code": "83024110",
            "quantity": 180,
            "unit_of_product": "PCS",
            "cgst_rate": 9,
            "sgst_rate": 9,
            "igst_rate": 0,
            "cess_rate": 0,
            "cessNonAdvol": 0,
            "taxable_amount": 8100
        }
    ]
}

if __name__ == "__main__":
    print("=" * 70)
    print("GENERATING NEW E-WAY BILL")
    print(f"Consignor: {payload['legal_name_of_consignor']} ({payload['gstin_of_consignor']})")
    print(f"Consignee: {payload['legal_name_of_consignee']} ({payload['gstin_of_consignee']})")
    print(f"Document: {payload['document_number']} dated {payload['document_date']}")
    print(f"Items: {len(payload['itemList'])}")
    print(f"Total Invoice Value: {payload['total_invoice_value']}")
    print("=" * 70)

    result = generate_ewaybill(payload)

    print("\n" + "=" * 70)
    print("FINAL RESULT")
    print("=" * 70)
    print(json.dumps(result, indent=2))
